version: "3"
services:
  db:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DB_URL: mongodb://db:27017/dealapp
    depends_on:
      - db
